apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-smooth-stork
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "956001729029"
    project: qwiklabs-gcp-04-75f1643b0aca
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: Git-Organisation
    repository: jenkinsxvaultcluster
  - key: staging
  - key: production
  ingress:
    domain: 34.72.112.17.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: kushwap1
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-tf-jx-smooth-stork-9cb438b37c7a
  - name: reports
    url: gs://reports-tf-jx-smooth-stork-9cb438b37c7a
  - name: repository
    url: gs://repository-tf-jx-smooth-stork-9cb438b37c7a
  vault: {}
  webhook: lighthouse
